### PR TITLE
feat: You can get Prs from github automatically

### PR DESCRIPTION
**Pull request by MRGUOKING**
Enter the button,you can get Prs from github automatically

### CODE REVIEW

**Comment by MRGUOKING** [comment]
https://user-images.githubusercontent.com/55344330/125249284-a2d48b00-e327-11eb-8a30-6048bd393dbc.mp4

demo [http://gona.work:9000/](http://gona.work:9000/)

**Comment by hsluoyz** [comment]
@Kininaru @sh1luo @1340908470 plz review.

**Review by Kininaru — COMMENTED** [review]
Code looks good, but I have a suggestion:

Using `get report` -> `set state` instead of refreshing the whole page.

**Comment by MRGUOKING** [comment]
@kingiw I have thought about it. but the front doesn't show the state directly. it shows the state by a function **getReportPrsAndText**  so that it can display in the form of markdown.  In this way , when the state change, the front end will not update directly. 
image

**Comment by kingiw** [comment]
> @kingiw I have thought about it. but the front doesn't show the state directly. it shows the state by a function **getReportPrsAndText** so that it can display in the form of markdown. In this way , when the state change, the front end will not update the changes directly. so I refresh the whole page. Do you have some advices to solve it?
> image

I'm not in charge of casbin oa. Maybe you should turn to @Kininaru

**Comment by hsluoyz** [comment]
@MRGUOKING PRs, not Prs

**Comment by MRGUOKING** [comment]
https://user-images.githubusercontent.com/55344330/126167498-40aafefc-4ad3-4a72-a4ee-da0c09461035.mp4

demo http://gona.work:9000/
account : admin password: 123

**Comment by MRGUOKING** [comment]
@hsluoyz This is the latest automatic weekly function

**Comment by hsluoyz** [comment]
@Kininaru @sh1luo @1340908470 plz review.

**Pull request merged**
